### model
model_name_or_path: meta-llama/Llama-3.2-3B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: all

### dataset
dataset: jfleg_all_corrections
template: llama3
cutoff_len: 512
overwrite_cache: true
preprocessing_num_workers: 4
dataloader_num_workers: 0

### output
output_dir: /home/models/llama32_3b_lora_factory
logging_steps: 5
save_steps: 50
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb
run_name: llama32-3b-lora

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 2.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
max_grad_norm: 1.0
gradient_checkpointing: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
eval_dataset: jfleg_all_corrections
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 25
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
