### model
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: all

### dataset
# NOTE: "knowledge_combined" includes Wikipedia + Wikidata + KILT WOW (all 3 sources)
# This model was trained but NOT selected for production.
# Production uses: llama31_8b_wikipedia_only_lora (Wikipedia-only, 8.8/10 quality)
# See: /home/docs/FINAL_MODEL_SELECTION.md
dataset: knowledge_combined
template: llama3
cutoff_len: 512
overwrite_cache: true
preprocessing_num_workers: 4
dataloader_num_workers: 0

### output
output_dir: /home/models/llama31_8b_knowledge_lora
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb
run_name: llama31-8b-knowledge-lora

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
max_grad_norm: 1.0
gradient_checkpointing: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 100
val_size: 0.01
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false

